services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./1_ddl.sql:/docker-entrypoint-initdb.d/1_ddl.sql
      - ./2_dml.sql:/docker-entrypoint-initdb.d/2_dml.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_USER=user
      - DB_PASSWORD=user_password
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=db

volumes:
  postgres-db-volume:
